# Generated by Django 4.2.6 on 2023-10-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='brend/images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='news/images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images')),
                ('title', models.CharField(max_length=51)),
                ('title_desc', models.CharField(max_length=300)),
                ('title_com', models.CharField(max_length=50)),
                ('title_com_desc', models.CharField(max_length=300)),
                ('title_ass', models.CharField(max_length=50)),
                ('title_ass_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='news/images')),
            ],
        ),
        migrations.CreateModel(
            name='Opesaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/images/opesaniya')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='partners/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=128, verbose_name='Brend nomi')),
                ('model', models.CharField(max_length=128, verbose_name='Maxsulot turi')),
                ('sert', models.CharField(max_length=128, verbose_name='Sertifikat')),
                ('product_name', models.CharField(max_length=200, verbose_name='Maxsulot nomi')),
                ('dioganal', models.CharField(blank=True, max_length=100, null=True)),
                ('protsesr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savol_Javoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xarakteristika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protssesor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('kesh', models.CharField(max_length=200)),
                ('chipset', models.CharField(max_length=200)),
                ('screen', models.CharField(max_length=200, verbose_name='Izobrajenia')),
                ('ekran', models.CharField(max_length=200)),
                ('tip', models.CharField(max_length=200)),
                ('matritsa', models.CharField(max_length=200)),
                ('chastota', models.CharField(max_length=200)),
                ('video_karta', models.CharField(max_length=200)),
                ('video_prot', models.CharField(max_length=200)),
                ('video_tip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Xaridordan_savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_turi', models.CharField(max_length=128)),
                ('javobi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('color', models.CharField(max_length=200)),
                ('quent', models.IntegerField(default=1)),
                ('memory', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('disc_price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('img', models.ManyToManyField(to='app.product_images')),
                ('opesaniya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.opesaniya')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_info')),
                ('vapros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.savol_javoblar')),
                ('xaraktristika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xarakteristika')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
