# Generated by Django 4.2.6 on 2023-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advert_brend_category_company_contact_main_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
