# Generated by Django 4.2.6 on 2024-01-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subctg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subctg_set', to='app.category'),
        ),
    ]
